apiVersion: v1
kind: ConfigMap
metadata:
  name: radicale-config
data:
  config: |
    [server]
    hosts: 0.0.0.0:5232

    [auth]
    type = http_x_remote_user

    [storage]
    filesystem_folder = /data/collections

    [web]
    type = internal

    [logging]
    level = info
---
apiVersion: v1
kind: Service
metadata:
  name: radicale
spec:
  selector:
    app: radicale
  ports:
    - name: dav
      port: 5232
      targetPort: 5232
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-pvc
  labels:
    app: radicale
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radicale
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radicale
  template:
    metadata:
      labels:
        app: radicale
    spec:
      containers:
        - name: radicale
          image: tomsquest/docker-radicale:latest
          ports:
            - name: dav
              containerPort: 5232
          volumeMounts:
            - name: collections
              mountPath: /data/collections
            - name: config
              mountPath: /config
      volumes:
        - name: collections
          persistentVolumeClaim:
            claimName: radicale-pvc
        - name: config
          configMap:
            name: radicale-config
